// <auto-generated />
using System;
using CoreApp.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace coreMVCDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230124065026_AddCategorytoDatabase")]
    partial class AddCategorytoDatabase 
    {
    }
}
